### ISSUE TITLE
output SMOKEReady files ptinv, pthour, ptday

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky#60] opened 2019-01-31 20:14 UTC
framework outputs them if configured. look in code for the following config variables.

```
[OutputSMOKEReadyFiles]
SEPARATE_SMOLDER = true
WRITE_PTINV_TOTALS = false
WRITE_PTDAY_FILE = false
SMOKE_PTINV_FILE=ptinv-%Y%m%d%H.ida
SMOKE_PTDAY_FILE=ptday-%Y%m%d%H.ems95
SMOKE_PTHOUR_FILE=pthour-%Y%m%d%H.ems95
COUNTRY_TO_PROCESS=US,USA,United States
```

smoke.py, under base...

attached BSF2PTDAY.R, which is Susan's R script that write two of the files.

----

## Attachments

https://trello-attachments.s3.amazonaws.com/557b6d216ba5a68657fb5344/5ab5464170654854687f7b82/d90a6c75202ea55504af0c57380e88b5/BSF2PTDAY.R

***(Programatically migrated from Trello)***

**Comment by Sillson** [comment] 2019-06-28 17:28
duplicate of https://github.com/pnwairfire/bluesky/issues/115

**Closed by Sillson** 2019-06-28 17:28 UTC
